# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Performance-related rules
    prefer_const_constructors: true  # Prefer using const constructors where possible
    prefer_const_literals_to_create_immutables: true  # Use const for immutable collections
    prefer_const_declarations: true  # Use const for variables that never change
    avoid_redundant_argument_values: true  # Avoid passing default values explicitly
    avoid_unnecessary_containers: true  # Avoid wrapping widgets in unnecessary containers
    use_rethrow_when_possible: true  # Use rethrow to preserve stack traces

    # Additional rules for better practices
    avoid_print: true  # Avoid using print statements in production code
    prefer_final_fields: true  # Use final for fields that are not reassigned
    unnecessary_this: true  # Avoid using `this` when not required
    prefer_single_quotes: true  # Prefer single quotes for strings
