// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEJLDdc1i_jlvwd0p3H54d1LQ1yZ1ZWVg',
    appId: '1:875996163443:web:2e3c9d2773c1df56ffa906',
    messagingSenderId: '875996163443',
    projectId: 'pixels-app-b38c4',
    authDomain: 'pixels-app-b38c4.firebaseapp.com',
    storageBucket: 'pixels-app-b38c4.firebasestorage.app',
    measurementId: 'G-6H51KPGZC7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVBUrPodKqCVdIDsR04Yt6BTKuEtBNcc0',
    appId: '1:875996163443:android:4f4a0553845079e4ffa906',
    messagingSenderId: '875996163443',
    projectId: 'pixels-app-b38c4',
    storageBucket: 'pixels-app-b38c4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzlgv3WO1JrxRjYfEad0-fQDlQ9imgD0c',
    appId: '1:875996163443:ios:b305c103cc2a1b57ffa906',
    messagingSenderId: '875996163443',
    projectId: 'pixels-app-b38c4',
    storageBucket: 'pixels-app-b38c4.firebasestorage.app',
    iosClientId: '875996163443-kl1bi1oqmqnc331536ig0ot4pmdcmufj.apps.googleusercontent.com',
    iosBundleId: 'com.example.pixelsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzlgv3WO1JrxRjYfEad0-fQDlQ9imgD0c',
    appId: '1:875996163443:ios:b305c103cc2a1b57ffa906',
    messagingSenderId: '875996163443',
    projectId: 'pixels-app-b38c4',
    storageBucket: 'pixels-app-b38c4.firebasestorage.app',
    iosClientId: '875996163443-kl1bi1oqmqnc331536ig0ot4pmdcmufj.apps.googleusercontent.com',
    iosBundleId: 'com.example.pixelsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEJLDdc1i_jlvwd0p3H54d1LQ1yZ1ZWVg',
    appId: '1:875996163443:web:3976b093c2363af8ffa906',
    messagingSenderId: '875996163443',
    projectId: 'pixels-app-b38c4',
    authDomain: 'pixels-app-b38c4.firebaseapp.com',
    storageBucket: 'pixels-app-b38c4.firebasestorage.app',
    measurementId: 'G-LFYW7K33WQ',
  );
}
